# Generated by Django 5.2.1 on 2025-05-10 03:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('servicio', models.CharField(choices=[('simultanea', 'Interpretación Simultánea'), ('consecutiva', 'Interpretación Consecutiva'), ('especializados', 'Servicios Especializados')], max_length=20)),
                ('fecha_evento', models.DateField()),
                ('horas_servicio', models.IntegerField()),
                ('metodo_pago', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_proyecto', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
